### PR TITLE
Tests for dic, aic, and bic

### PR DESCRIPTION
**Pull request by itsdfish**
Rob,

I added some tests to make sure dic, aic, and bic run and at least their qualitative properties are preserved. I would like to add tests for waic and psisloo also. Do you have a ground truth to which we can compare? Otherwise, I will suggest reading in simulated data and comparing output from StatsModelComparisons to corresponding output from R.

### CODE REVIEW

**Comment by goedman** [comment]
Hi Chris, thanks for doing that. I would suggest to use the car data for those tests because we can directly compare with R and also the Statistical Rethinking results. Maybe that is possible by storing the ll matrix in the repo? For the car data waic and psisloo are also very comparable.

**Comment by goedman** [comment]
At some point, now you’ve added dic, aic and bic, I would like to show an example, not so much a test, where they start to really differ. Non-Normal and hierarchical models.

**Comment by goedman** [comment]
Forgot that when testing we do have StanSample.jl available so we can use that instead of storing the ll matrix, possibly combined with Random.seed!()

**Comment by itsdfish** [comment]
Hi Rob,

I was thinking about going one step further by storing the MCMC samples to ensure the respective Julia and R functions process the same inputs. That should provide a more rigorous test. I'll look into the feasibility of this approach over the weekend. If that turns out to be arduous, we can compare the mean and standard errors of each metric.

**Comment by goedman** [comment]
Sounds a good approach. If we store a common set of .csv files say for the cars example we could use those for testing in R and StatsModelComparisons.jl and in fact remove dependencies on StanSample.jl and building cmdstan while testing. The arsenic test is better as an example.

**Pull request merged**
